# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'RJCategoryTool' do
  
  pod 'Masonry'
  
  pod 'GTMBase64'
  
  #  pod 'AFNetworking'
  #
  #  pod 'SDWebImage'
  #
  #  pod 'MJExtension'
  #
  #  pod 'MJRefresh'
  #
  #  pod 'SDCycleScrollView'
  #
  #  pod 'MBProgressHUD'
  #
  #  pod 'Toast'
  #
  #  #pod 'ZLPhotoBrowser'
  #  pod 'ZLPhotoBrowser', '~> 3.0.6'
  #
  #  pod 'RTRootNavigationController'
  #
  #  pod 'ReactiveObjC'
  #
  #  pod 'FMDB'
  #
  #  pod 'WechatOpenSDK'
  #
  #  pod 'AlipaySDK-iOS'
  #
  #  pod 'LYEmptyView'
  #
  #  pod 'UITableView+FDTemplateLayoutCell'
  #
  #  #pod 'GPUImage'
end
